CREATE DATABASE IF NOT EXISTS edufy;

USE edufy;

CREATE TABLE IF NOT EXISTS tutors (
	tutorUserName VARCHAR(100) PRIMARY KEY NOT NULL
	, firstName VARCHAR(100) NOT NULL
	, lastName VARCHAR(100) NOT NULL
  , pass VARCHAR(100) NOT NULL
  , rating FLOAT(12) NOT NULL DEFAULT 5
  , sessions INT(12) NOT NULL DEFAULT 1
	, picUrl VARCHAR(100) DEFAULT NULL
	, liberalArts BOOLEAN NOT NULL DEFAULT FALSE
	, business BOOLEAN NOT NULL DEFAULT FALSE
	, engineering BOOLEAN NOT NULL DEFAULT FALSE
	, mathematics BOOLEAN NOT NULL DEFAULT FALSE
	, biology BOOLEAN NOT NULL DEFAULT FALSE
	, chemistry BOOLEAN NOT NULL DEFAULT FALSE
	, computerScience BOOLEAN NOT NULL DEFAULT FALSE
	, geology BOOLEAN NOT NULL DEFAULT FALSE
	, physics BOOLEAN NOT NULL DEFAULT FALSE
	, specificClasses TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS students (
	studentUserName VARCHAR(100) PRIMARY KEY NOT NULL
	, firstName VARCHAR(100) NOT NULL
	, lastName VARCHAR(100) NOT NULL
  , pass VARCHAR(100) NOT NULL
	, picUrl VARCHAR(100) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS availability (
	id INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT
	, tutorUserName VARCHAR(100) NOT NULL
	, date VARCHAR(100) NOT NULL
	, startTimes TEXT NOT NULL

  , FOREIGN KEY (tutorUserName)
		REFERENCES tutors(tutorUserName) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS appointments (
	id INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT
	, tutorUserName VARCHAR(100) NOT NULL
	, studentUserName VARCHAR(100) NOT NULL
	, date VARCHAR(100) NOT NULL

  ,FOREIGN KEY (tutorUserName)
		REFERENCES tutors(tutorUserName) ON DELETE CASCADE

	,FOREIGN KEY (studentUserName)
		REFERENCES students(studentUserName) ON DELETE CASCADE
);
