CREATE DATABASE IF NOT EXISTS edufy;

USE edufy;

CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(60) NOT NULL PRIMARY KEY,
  password VARCHAR(65) NOT NULL,
  accountType SET('student', 'tutor') NOT NULL,
)

CREATE TABLE IF NOT EXISTS tutors (
	username VARCHAR(100) PRIMARY KEY NOT NULL,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  picUrl VARCHAR(100) DEFAULT NULL,
  rating FLOAT(12) NOT NULL DEFAULT 5,
  sessions INT(12) NOT NULL DEFAULT 1,
  liberalArts BOOLEAN NOT NULL DEFAULT FALSE,
  business BOOLEAN NOT NULL DEFAULT FALSE,
  engineering BOOLEAN NOT NULL DEFAULT FALSE,
  mathematics BOOLEAN NOT NULL DEFAULT FALSE,
  biology BOOLEAN NOT NULL DEFAULT FALSE,
  chemistry BOOLEAN NOT NULL DEFAULT FALSE,
  computerScience BOOLEAN NOT NULL DEFAULT FALSE,
  geology BOOLEAN NOT NULL DEFAULT FALSE,
  physics BOOLEAN NOT NULL DEFAULT FALSE,
  specificClasses TEXT DEFAULT NULL,
  FOREIGN KEY (username) REFERENCES users (username)
);

CREATE TABLE IF NOT EXISTS students (
	username VARCHAR(100) PRIMARY KEY NOT NULL,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  picUrl VARCHAR(100) DEFAULT NULL,
  FOREIGN KEY (username) REFERENCES users (username)
);

CREATE TABLE IF NOT EXISTS availability (
  tutorUserName VARCHAR(100) NOT NULL,
  date VARCHAR(100) NOT NULL,
  startTimes TEXT NOT NULL,
  FOREIGN KEY (tutorUserName) REFERENCES tutors (username)
);

CREATE TABLE IF NOT EXISTS appointments (
  tutorUserName VARCHAR(100) NOT NULL,
  studentUserName VARCHAR(100) NOT NULL,
  subject VARCHAR(100) NOT NULL,
  date VARCHAR(100) NOT NULL,
  endTimes VARCHAR(100) NOT NULL,
  FOREIGN KEY (tutorUserName) REFERENCES tutors (username),
  FOREIGN KEY (studentUserName) REFERENCES students (username)
);
